# Generated by Django 3.1 on 2020-08-15 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_howyouknowus'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='howyouknowus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.howyouknowus'),
        ),
    ]
