# Generated by Django 3.1 on 2020-08-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signup_howyouknowus'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='tedxExperience',
            field=models.BooleanField(null=True),
        ),
    ]
