# Generated by Django 3.1 on 2020-08-15 21:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200815_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Typeofparticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='workwithus',
            name='callnumber',
        ),
        migrations.AddField(
            model_name='sponser',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AddField(
            model_name='sponser',
            name='describtion',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='sponser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d(9,15)$')]),
        ),
        migrations.AddField(
            model_name='sponser',
            name='whatyoudo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workwithus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d(9,15)$')]),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='degree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.degree'),
        ),
        migrations.AddField(
            model_name='sponser',
            name='typeofparticipation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.typeofparticipation'),
        ),
    ]
