# Generated by Django 3.1 on 2020-08-20 13:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroSpeaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d(9,15)$')])),
                ('work', models.CharField(max_length=50)),
                ('yourname', models.CharField(max_length=50)),
                ('youremail', models.EmailField(max_length=254)),
                ('yourphone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d(9,15)$')])),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
                ('typeofparticipation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.typeofparticipation')),
            ],
        ),
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
