# Generated by Django 3.1 on 2020-08-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200820_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='long_description',
            field=models.TextField(),
        ),
    ]
