# Generated by Django 3.1 on 2020-08-21 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200820_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=56)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('whatyoudo', models.CharField(max_length=50, null=True)),
                ('describtion', models.CharField(max_length=3000, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city')),
                ('typeofparticipation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.typeofparticipation')),
            ],
        ),
        migrations.AlterField(
            model_name='introspeaker',
            name='city',
            field=models.ForeignKey(default={''}, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
        migrations.AlterField(
            model_name='introspeaker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='introspeaker',
            name='typeofparticipation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.typeofparticipation'),
        ),
        migrations.AlterField(
            model_name='introspeaker',
            name='youremail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='introspeaker',
            name='yourphone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.DeleteModel(
            name='Sponser',
        ),
    ]
