# Generated by Django 3.1 on 2020-08-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200821_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('title', models.CharField(max_length=56)),
                ('instagram', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='describtion',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='whatyoudo',
        ),
    ]
