# Generated by Django 3.1 on 2020-08-21 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Typeofparticipation',
            new_name='Activity',
        ),
        migrations.DeleteModel(
            name='HowYouKnowUs',
        ),
        migrations.RenameField(
            model_name='introspeaker',
            old_name='typeofparticipation',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='typeofparticipation',
        ),
        migrations.AddField(
            model_name='degree',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='introspeaker',
            name='why',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='activity',
            field=models.CharField(default='asd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='participation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.participation'),
        ),
    ]
