# Generated by Django 3.1 on 2020-08-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200822_0315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='workwithus',
            name='field',
            field=models.TextField(),
        ),
    ]
